### ISSUE TITLE
solution to the bug while running app2.py

### ISSUE THREAD

**Issue by shekharkhetan** [TPRU-demo/pitaxcalc-demo#66]
@martinholmer @andersonfrailey 
Can you please guide on how to solve this issue? It seems to be some software issue. But i have reinstalled anaconda after deleting & deinstalling the earlier version. This error is received after running app2.py file.

```````````````````````````
(base) C:\Users\DC-2 TPRU\Desktop\WB training-3\pitaxcalc-demo>python app2.py
sys:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "app2.py", line 8, in <module>
    recs = Records()
  File "C:\Users\DC-2 TPRU\Desktop\WB training-3\pitaxcalc-demo\taxcalc\records.py", line 93, in __init__
    self._read_data(data)
  File "C:\Users\DC-2 TPRU\Desktop\WB training-3\pitaxcalc-demo\taxcalc\records.py", line 261, in _read_data
    taxdf[varname].astype(np.int32).values)
  File "C:\Users\DC-2 TPRU\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\DC-2 TPRU\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5001, in astype
    **kwargs)
  File "C:\Users\DC-2 TPRU\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3714, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "C:\Users\DC-2 TPRU\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3581, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\DC-2 TPRU\Anaconda3\lib\site-packages\pandas\core\internals.py", line 575, in astype
    **kwargs)
  File "C:\Users\DC-2 TPRU\Anaconda3\lib\site-packages\pandas\core\internals.py", line 664, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "C:\Users\DC-2 TPRU\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 702, in astype_nansafe
    raise ValueError('Cannot convert non-finite values (NA or inf) to '
ValueError: Cannot convert non-finite values (NA or inf) to integer
`````````````````````````````````````````````

**Comment by andersonfrailey** [comment]
@shekharkhetan, I believe this is related to the issue reported in #64. It seems like your data has missing variables and that's causing the error you're seeing.

**Comment by martinholmer** [comment]
@shekharkhetan, I agree with @andersonfrailey's analysis that your new input data set is faulty.
In particular, the error message you're getting (see below) suggests your new data set has blanks (NA) or some other non-finite number.  Please scan your new input data set for problems.
```
File "C:\Users\DC-2 TPRU\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 702, in astype_nansafe
    raise ValueError('Cannot convert non-finite values (NA or inf) to '
ValueError: Cannot convert non-finite values (NA or inf) to integer
```
Again, this is not a problem with your Anaconda installation.  These errors clearly indicate that your now input data set includes values that cannot be sensibly converted into integer numbers.

**Comment by sebastiansajie** [comment]
Shekhar, you may need to clean the input data (pit.csv). It may have characters such as '.' to denote blanks. Do a quick check of the data.

**Comment by shekharkhetan** [comment]
@andersonfrailey @martinholmer  @sebastiansajie Thanks for the suggestions as the data file had missing value and it ran after the corrections. Will keep in mind in future about this bug.
